image: alpine/latest
packages:
  - hut
  - go
oauth: git.sr.ht/OBJECTS:RW git.sr.ht/PROFILE:RO git.sr.ht/REPOSITORIES:RO pages.sr.ht/PAGES:RW
environment:
  site: goldberg.farthergate.com

sources:
  - https://git.sr.ht/~aleksrutins/goldberg
  - https://git.sr.ht/~aleksrutins/cicada

tasks:
  - pkl: |
      curl -L -o pkl 'https://github.com/apple/pkl/releases/download/0.30.2/pkl-alpine-linux-amd64'
      chmod +x pkl
      ./pkl --version
      sudo mv pkl /usr/bin/
  - build-publish: |
      cd goldberg
      if ../cicada/cicada commit "[release"; then
        go run main.go
      fi
  - pkldoc: |
      cd goldberg
      wget -O pkldoc https://github.com/apple/pkl/releases/download/0.30.2/pkldoc-alpine-linux-amd64
      chmod +x pkldoc
      ./pkldoc -o dist $(find pkl/ -name '*.pkl')
  - package-site: |
      cd goldberg
      cp -rv pkl/* dist/
      tar -C dist --hard-dereference -cvhz . > ../site.tar.gz
  - upload-site: |
      hut pages publish -d $site site.tar.gz
