image: alpine/latest
packages:
  - hut
  - go
oauth: git.sr.ht/OBJECTS:RW git.sr.ht/PROFILE:RO git.sr.ht/REPOSITORIES:RO pages.sr.ht/PAGES:RW
environment:
  site: goldberg.farthergate.com
  pkl_version: 0.30.2
  CLICOLOR_FORCE: "1"

tasks:
  - pkl-install: |
      wget -O pkl https://github.com/apple/pkl/releases/download/$pkl_version/pkl-alpine-linux-amd64
      wget -O pkldoc https://github.com/apple/pkl/releases/download/$pkl_version/pkldoc-alpine-linux-amd64

      chmod +x pkl
      ./pkl --version
      sudo mv pkl /usr/bin/

      chmod +x pkldoc
      ./pkldoc --version
      sudo mv pkldoc /usr/bin/
  - build-publish: |
      cd goldberg
      go run main.go
