image: fedora/43
packages:
  - hut
  - wget
  - tar
  - gzip
  - java-latest-openjdk-devel
oauth: git.sr.ht/OBJECTS:RW git.sr.ht/PROFILE:RO git.sr.ht/REPOSITORIES:RO pages.sr.ht/PAGES:RW
environment:
  site: goldberg.farthergate.com
  pkl_version: 0.30.2
  CLICOLOR_FORCE: "1"

tasks:
  - deps: |
      curl https://cache.farthergate.com/install.sh | bash -s -- pkl pkldoc forester
  - build-publish: |
      cd goldberg
      ./mvnw package
      
