/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
    id("org.pkl-lang") version "0.30.2"
    kotlin("jvm") version "2.3.0"
    kotlin("plugin.serialization") version "2.3.0"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.1")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation("org.pkl-lang:pkl-config-java:0.30.2")
    implementation("org.pkl-lang:pkl-config-kotlin:0.30.2")
    implementation("org.pkl-lang:pkl-codegen-kotlin:0.30.2")
    implementation("net.mamoe.yamlkt:yamlkt:0.13.0")
    implementation("com.github.ajalt.clikt:clikt:5.1.0")
    implementation("com.github.ajalt.mordant:mordant:3.0.2")
    implementation("com.github.ajalt.colormath:colormath:3.6.1")
}

group = "com.farthergate"
version = "0.5.2"
description = "goldberg"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks {
    register<Jar>("fatJar") {
        dependsOn.addAll(listOf("compileJava", "compileKotlin", "processResources")) // We need this for Gradle optimization to work
        archiveClassifier.set("standalone") // Naming the jar
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        manifest { attributes(mapOf("Main-Class" to application.mainClass, "Multi-Release" to "true")) } // Provided we set it up in the application plugin configuration
        val sourcesMain = sourceSets.main.get()
        val contents = configurations.runtimeClasspath.get()
            .map { if (it.isDirectory) it else zipTree(it) } +
                sourcesMain.output
        from(contents)
    }
}

//pkl {
//    kotlinCodeGenerators {
//        register("genKotlin") {
//            sourceModules.addAll(files("pkl/Config.pkl"))
//        }
//    }
//    pkldocGenerators {
//        register("pkldoc") {
//            sourceModules.addAll(file("pkl").walkTopDown().filter {it.isFile() && it.extension == "pkl"}.toList().map { file(it.path).toURI() })
//        }
//    }
//}