/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "goldberg"

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

pluginManagement {
    repositories {
        mavenCentral()
    }
}